name: Document Code
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        run: "mkdir Documentation && echo <h1>hello</h1> > Documentation/index.html"
        #uses: SwiftDocOrg/swift-doc@master
        #with:
        #  inputs: Sources/CasePaths
        #  module-name: CasePaths
        #  format: html
        #  output: Documentation
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Documentation
