name: Document Code
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          base-url: /scptest/
          inputs: Sources/CasePaths
          module-name: CasePaths
          format: html
          output: Documentation
      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v2
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Documentation
